# archivo: _config.yml 
title: "Interactive IR and Raman"
author: Dr. Mounir Mensi, Dr. Kevin Jablonka and  Antonio Doñez
logo:  images/logo-LSMO.png
#
launch_buttons:
  colab_url      : https://colab.research.google.com # The URL of Google Colab (e.g., https://colab.research.google.com)
  binderhub_url  : https://mybinder.org
  thebe          : true
  jupyterhub_url : https://noto.epfl.ch

notebook_interface : "notebook"

html:
  home_page_in_navbar         : false

repository:
  url            : https://github.com/AntonioCd96/IR-and-Raman.git  # The URL to your book's repository

latex:
  latex_engine : "xelatex"      
  latex_documents:
    targetname: book.tex


bibtex_bibfiles:
  - references.bib

sphinx:
  config:
    bibtex_reference_style: author_year
    html_js_files:
    - https://cdnjs.cloudflare.com/ajax/libs/require.js/2.3.4/require.min.js
    mathjax_path: https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js
    mathjax3_config:
      TeX:
        Macros:
          "N": "\\mathbb{N}"
          "floor": ["\\lfloor#1\\rfloor", 1]
          "bmat" : ["\\left[\\begin{array}"]
          "emat" : ["\\end{array}\\right]"]

execute:
  execute_notebooks: force


parse:
  myst_enable_extensions:
    # don't forget to list any other extensions you want enabled,
    # including those that are enabled by default!
    - amsmath
    - dollarmath
    - linkify
    - substitution
    - colon_fence
    - deflist
    - html_admonition
    - html_image
    - replacements
    - smartquotes
html:
  use_issues_button: true
  use_multitoc_numbering: true
  use_repository_button: true